'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let saved;try{saved=new Set(JSON.parse(localStorage.getItem('derdo-saved')||'[]').filter(id=>PLACES.some(p=>p.id===id)));}catch{saved=new Set()}
let category='',onlySaved=false,limit=9,lastFocus=null;
const cat=id=>CATEGORIES.find(c=>c.id===id),norm=s=>s.toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i');
const exactImages={'Topkapı Sarayı':'topkapi','Dolmabahçe Sarayı':'palace','İstanbul Arkeoloji Müzeleri':'museum','Galata Kulesi':'istanbul','Yerebatan Sarnıcı':'cistern','Sultanahmet Camii':'mosque'};
const photo=p=>exactImages[p.name]||cat(p.category).image;
const caption=p=>exactImages[p.name]?p.name:'Kategori görseli · '+cat(p.category).name;
function notify(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').classList.remove('visible'),2300)}
function toggleSave(id){if(saved.has(id)){saved.delete(id);notify('Keşif listenden kaldırıldı')}else{saved.add(id);notify('Keşif listene eklendi')}try{localStorage.setItem('derdo-saved',JSON.stringify([...saved]))}catch{notify('Bu tarayıcıda kalıcı kayıt kullanılamıyor')}$('#saved-count').textContent=saved.size;renderPlaces();const b=$('#detail-save');if(b){b.textContent=saved.has(id)?'♥ Listemde':'♡ Listeme ekle'}}
function selectCategory(id){category=id;onlySaved=false;limit=9;$('#search').value='';$('#era').value='';$('#district').value='';renderPlaces();$('#yerler').scrollIntoView({behavior:'smooth'})}
$('#categories').innerHTML=CATEGORIES.map((c,i)=>`<button class="category" data-category="${c.id}" aria-label="${c.name} kategorisini keşfet"><img src="/assets/${c.image}.jpg" alt="${c.name} için İstanbul’dan bir görünüm" loading="lazy"><span class="cat-number">0${i+1}</span><div class="cat-content"><small>${c.tag}</small><h3>${c.name}</h3><div class="cat-row"><span>${PLACES.filter(p=>p.category===c.id).length} keşif noktası</span><b>↗</b></div></div></button>`).join('');
$('#categories').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(b)selectCategory(b.dataset.category)});
for(const [selector,key] of [['#era','era'],['#district','district']]){$(selector).innerHTML += [...new Set(PLACES.map(p=>p[key]))].sort((a,b)=>a.localeCompare(b,'tr')).map(s=>`<option>${esc(s)}</option>`).join('');$(selector).addEventListener('change',()=>{limit=9;renderPlaces()})}
$('#search').addEventListener('input',()=>{limit=9;renderPlaces()});
function renderPlaces(){
 const q=norm($('#search').value.trim());const found=PLACES.filter(p=>(!category||p.category===category)&&(!onlySaved||saved.has(p.id))&&(!$('#era').value||p.era===$('#era').value)&&(!$('#district').value||p.district===$('#district').value)&&(!q||norm([p.name,p.district,p.era,p.story,cat(p.category).name].join(' ')).includes(q)));
 $('#catalogue-title').innerHTML=onlySaved?'Senin <em>keşif listen.</em>':category?esc(cat(category).name):'Şehrin izini <em>sür.</em>';
 $('#result-count').textContent=found.length+' yer · '+PLACES.length+' kayıtlık atlas';
 $('#filters').innerHTML=[{id:'',name:'Tümünü keşfet'},...CATEGORIES].map(c=>`<button class="chip ${category===c.id?'active':''}" data-filter="${c.id}" aria-pressed="${category===c.id}">${c.name}</button>`).join('');
 $('#active-state').innerHTML=onlySaved?'<span>Bu liste yalnızca kullandığın tarayıcıda saklanır.</span> <button class="text-link" id="show-all">Tüm yerlere dön</button>':'';
 $('#places').innerHTML=found.slice(0,limit).map(p=>`<article class="place"><button class="bookmark ${saved.has(p.id)?'selected':''}" data-save="${p.id}" aria-label="${esc(p.name)}: ${saved.has(p.id)?'listeden çıkar':'listeme ekle'}" aria-pressed="${saved.has(p.id)}">${saved.has(p.id)?'♥':'♡'}</button><button class="place-open" data-place="${p.id}" aria-label="${esc(p.name)} hakkında oku"><div class="place-photo"><img src="/assets/${photo(p)}.jpg" alt="${esc(caption(p))}" loading="lazy">${exactImages[p.name]?'':'<span class="photo-label">KATEGORİ GÖRSELİ</span>'}</div><div class="place-content"><div class="place-meta"><span>${esc(p.district.toLocaleUpperCase('tr'))}</span><span>${esc(p.date)}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.story)}</p><div class="place-foot"><span>${esc(cat(p.category).name)}</span><span>↗</span></div></div></button></article>`).join('')||'<div class="empty"><h3>Burada henüz bir eşleşme yok.</h3><p>Aramanı değiştir veya filtreleri temizleyerek yeniden keşfet.</p><button class="text-link" id="reset">Filtreleri temizle</button></div>';
 $('#more').hidden=found.length<=limit;
}
$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(b){category=b.dataset.filter;limit=9;renderPlaces()}});
$('#places').addEventListener('click',e=>{const save=e.target.closest('[data-save]'),p=e.target.closest('[data-place]');if(save)toggleSave(save.dataset.save);else if(p)openPlace(p.dataset.place);else if(e.target.closest('#reset')){selectCategory('')}});
$('#active-state').addEventListener('click',e=>{if(e.target.closest('#show-all'))selectCategory('')});
$('#more').addEventListener('click',()=>{limit+=9;renderPlaces()});
$('#saved-button').addEventListener('click',()=>{onlySaved=true;category='';limit=9;$('#search').value='';$('#era').value='';$('#district').value='';renderPlaces();$('#yerler').scrollIntoView({behavior:'smooth'})});
const dialog=$('#detail');function showDialog(html){if(!dialog.open)lastFocus=document.activeElement;$('#dialog-body').innerHTML=html;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;document.body.style.overflow='hidden';$('#close-dialog').focus()}
function closeDialog(){dialog.close()}
$('#close-dialog').addEventListener('click',closeDialog);dialog.addEventListener('close',()=>{document.body.style.overflow='';if(lastFocus?.isConnected)lastFocus.focus()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog()}});
function openPlace(id){const p=PLACES.find(p=>p.id===id);if(!p)return;const extra=EXTRA[id],source=SOURCES[p.source]||SOURCES.city;const official=extra?.link||source[1];
 showDialog(`<div class="detail-cover"><img src="/assets/${photo(p)}.jpg" alt="${esc(caption(p))}"><span class="photo-label">${esc(caption(p))}</span></div><div class="detail-content"><p class="eyebrow">${cat(p.category).tag}</p><h2>${esc(p.name)}</h2><div class="detail-facts"><span>⌖ ${esc(p.district)} · İstanbul</span><span>${esc(p.era)}</span><span>${esc(p.date)}</span></div><h3>Bir yerin hikâyesi</h3><p>${esc(p.story)}</p>${extra?`<h3>Tarihin içinden</h3><p>${esc(extra.history)}</p><h3>Mimariyi okumak</h3><p>${esc(extra.architecture)}</p>`:''}<h3>Bakmadan geçme</h3><p>${esc(p.look)}</p><h3>Ziyaretini planla</h3><p>${p.category==='inanc'?'İbadet düzenine, kıyafet kurallarına ve ziyaretçi alanlarına dikkat et. ':''}Açık bölümler, restorasyon çalışmaları, giriş ücretleri ve ziyaret saatleri değişebilir. Yola çıkmadan önce kurumun güncel duyurusunu kontrol et.</p><div class="detail-actions"><button id="detail-save" data-save="${id}">${saved.has(id)?'♥ Listemde':'♡ Listeme ekle'}</button><a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.name+' İstanbul '+p.district)}" target="_blank" rel="noopener">Haritada ara ↗</a><button data-share="${id}">Bağlantıyı kopyala ↗</button></div><p class="source-note">Kaynak ve güncel ziyaret bilgileri: <a href="${official}" target="_blank" rel="noopener">${esc(source[0])} ↗</a><br>Tarihî dönem etiketi, yapının ilk ya da baskın katmanını gösterir; sonraki dönüşümleri dışlamaz.</p></div>`);
}
$('#dialog-body').addEventListener('click',async e=>{const save=e.target.closest('[data-save]'),place=e.target.closest('[data-place]'),share=e.target.closest('[data-share]');if(save)toggleSave(save.dataset.save);else if(place)openPlace(place.dataset.place);else if(share){const u=new URL(location.href);u.hash='yer-'+share.dataset.share;try{await navigator.clipboard.writeText(u.href);notify('Yer bağlantısı kopyalandı')}catch{notify('Kopyalama kullanılamıyor. Adres çubuğundaki bağlantıyı kullanabilirsin.');location.hash=u.hash}}});
$('#routes').innerHTML=ROUTES.map((r,i)=>`<button class="route-card" data-route="${i}"><img src="/assets/${r.image}.jpg" alt="${r.name} rotası için kategori görseli" loading="lazy"><small>${r.label}</small><h3>${r.name}</h3><p>${r.desc}</p><div class="route-bottom"><span>${r.stops.length} durak · Öneri rotası</span><span>↗</span></div></button>`).join('');
$('#routes').addEventListener('click',e=>{const b=e.target.closest('[data-route]');if(!b)return;const r=ROUTES[Number(b.dataset.route)];showDialog(`<div class="detail-cover"><img src="/assets/${r.image}.jpg" alt="Rota kategori görseli"></div><div class="detail-content"><p class="eyebrow">${r.label}</p><h2>${r.name}</h2><p>${r.desc}</p><p>Duraklar keşif sırasına göre önerilmiştir. Bu bir canlı navigasyon rotası değildir; mesafeleri ve ulaşımı harita üzerinden kontrol et. İç mekânları gezmek istersen rotayı birden fazla güne bölebilirsin.</p>${r.stops.map((id,i)=>{const p=PLACES.find(p=>p.id===id);return `<button class="stop" data-place="${id}"><span class="num">${i+1}</span><span class="stop-title">${p.name}<small>${p.district} · ${cat(p.category).name}</small></span></button>`}).join('')}</div>`)});
$('#timeline-button').addEventListener('click',()=>showDialog(`<div class="detail-content"><p class="eyebrow">ŞEHRİN HİKÂYESİ</p><h2>Çağlar boyunca <em>İstanbul.</em></h2><p>Bir kentin değişimi, yalnız hükümdarlar ve tarihlerle değil; su yolları, limanları, ibadethaneleri ve evleriyle de okunur.</p>${[
['Antik Çağ','Boğaz kıyısında bir yerleşim','Byzantion ve karşı kıyıdaki Khalkedon, kentin antik yerleşim katmanının parçalarıdır. Boğaz’daki konum, deniz yolları ve ticaret açısından belirleyiciydi.'],
['330','Yeni bir başkent','Konstantinopolis’in başkent olması, meydanlar ve anıtsal yapılarla kentin ölçeğini değiştirdi. Hipodrom ve su altyapısı bu başkent yaşamının izlerini taşır.'],
['6. yüzyıl','Kubbeler ve yeraltındaki şehir','Justinianus dönemindeki Ayasofya ve Yerebatan gibi yapılar, başkentin mimari ve mühendislik dünyasını anlamak için önemli duraklardır.'],
['1453 ve sonrası','Osmanlı başkenti','Fetihten sonra saraylar, külliyeler, çarşılar ve mahalleler eski şehrin üzerine yeni katmanlar ekledi. Topkapı ve Süleymaniye bu değişimin anıtsal örnekleridir.'],
['19. yüzyıl','Boğaz’a açılan bir kent','Kıyı sarayları, garlar, pasajlar ve apartmanlar yeni bir şehir hayatının izlerini taşır. Mimari dil ve ulaşım ağları birlikte değişti.'],
['Cumhuriyet ve bugün','Yaşayan miras','Müzeler, sanat kurumları ve koruma çalışmaları, tarihî yapıları yeni işlevlerle buluşturdu. İstanbul’un hikâyesi bugün de yaşayan mahallelerinde devam ediyor.']
].map(([t,h,p])=>`<div class="timeline-item"><strong>${t}</strong><h3>${h}</h3><p>${p}</p></div>`).join('')}<p class="source-note">Genel okuma: <a href="https://whc.unesco.org/en/list/356/" target="_blank" rel="noopener">UNESCO</a> · <a href="https://istanbul.ktb.gov.tr/" target="_blank" rel="noopener">İstanbul İl Kültür ve Turizm Müdürlüğü</a></p></div>`));
$('#sources-button').addEventListener('click',()=>showDialog(`<div class="detail-content"><p class="eyebrow">EDİTORYAL NOT</p><h2>Kaynaklar & görseller</h2><p>Derdoİstanbul bağımsız bir kültür rehberidir. İçerikler kısa editoryal anlatımlardır; resmî eser envanteri veya bilet satış hizmeti sunmaz. Müze koleksiyonlarının açık bölümleri ve ziyaret koşulları için doğrudan kurum bilgileri esas alınmalıdır.</p><div class="source-list">${Object.values(SOURCES).map(([n,u])=>`<a href="${u}" target="_blank" rel="noopener">${n} ↗</a>`).join('')}<a href="https://sakipsabancimuzesi.org/" target="_blank" rel="noopener">Sakıp Sabancı Müzesi ↗</a><a href="https://www.rmk-museum.org.tr/" target="_blank" rel="noopener">Rahmi M. Koç Müzesi ↗</a></div><h3>Fotoğraflar hakkında</h3><p>Galata ve şehir görselleri: Unsplash. Saray görselleri: Milli Saraylar. Arkeoloji Müzesi görseli: Kültür ve Turizm Bakanlığı. Tek bir yapıya ait olmayan kart görselleri “kategori görseli” olarak işaretlenmiştir; ilgili yerin birebir fotoğrafı olarak sunulmaz.</p><h3>Keşif listen</h3><p>Kaydedilen yerler yalnız kullandığın tarayıcının yerel depolamasında tutulur. Üyelik gerektirmez ve sunucuya gönderilmez. Tarayıcı verileri temizlendiğinde liste de silinir.</p></div>`));
$('#saved-count').textContent=saved.size;renderPlaces();function readHash(){const m=location.hash.match(/^#yer-(\d+)$/);if(m)openPlace(m[1])}window.addEventListener('hashchange',readHash);readHash();
