const CATEGORIES = [
{id:'saray',name:'Saraylar & Kasırlar',tag:'İMPARATORLUĞUN İZİNDE',image:'palace',desc:'Avlulardan Boğaz kıyısındaki görkemli saraylara.'},
{id:'muze',name:'Müzeler & Koleksiyonlar',tag:'HAFIZANIN ODALARI',image:'museum',desc:'Arkeoloji, sanat, bilim ve şehrin yaşayan belleği.'},
{id:'inanc',name:'İnanç & Mimari',tag:'KUBBELERİN ALTINDA',image:'mosque',desc:'Camiler, kiliseler ve çok katmanlı bir kültür.'},
{id:'antik',name:'Surlar & Sarnıçlar',tag:'YERİN ALTINDA, ZAMANIN ÖTESİNDE',image:'cistern',desc:'Antik başkentin mühendisliği ve savunma mirası.'},
{id:'semt',name:'Semtler & Sokaklar',tag:'ŞEHRİN RUHU',image:'istanbul',desc:'Bir mahallenin hikâyesi, bir sokağın hafızası.'},
{id:'carsi',name:'Çarşılar & Hanlar',tag:'YAŞAYAN GELENEK',image:'city',desc:'Ticaretin, zanaatın ve gündelik hayatın izleri.'},
{id:'bosphorus',name:'Boğaz & Yeşil İstanbul',tag:'İKİ KIYI ARASINDA',image:'bosphorus',desc:'Yalılar, korular, adalar ve kıyı manzaraları.'},
{id:'sivil',name:'Sivil Mimari & Anıtlar',tag:'TAŞA YAZILAN HİKÂYELER',image:'istanbul',desc:'Kuleler, garlar, meydanlar ve zarif şehir yapıları.'}
];
const SOURCES={unesco:['UNESCO · İstanbul’un Tarihi Alanları','https://whc.unesco.org/en/list/356/'],palace:['Milli Saraylar','https://www.millisaraylar.gov.tr/'],museum:['Kültür ve Turizm Bakanlığı · Müzeler','https://muze.gov.tr/muzeler'],city:['İstanbul İl Kültür ve Turizm Müdürlüğü','https://istanbul.ktb.gov.tr/'],cistern:['Kültür ve Turizm Müdürlüğü · Sarnıçlar ve kemerler','https://istanbul.ktb.gov.tr/TR-276812/sarniclar-kemerler.html']};
const ROWS=`
Topkapı Sarayı|saray|Fatih|Osmanlı|15. yüzyıl|Sarayburnu’nda avlular, köşkler ve bahçeler üzerinden büyüyen bir yönetim ve yaşam kompleksi. Tek bir anıtsal bina yerine birbirine açılan mekânlarıyla Osmanlı saray düzenini anlatır.|Bâbüsselâm, Divan avlusu, Bağdat Köşkü ve çini bezemeleri.|palace
Dolmabahçe Sarayı|saray|Beşiktaş|Osmanlı|19. yüzyıl|Boğaz’a uzanan cepheleriyle Osmanlı saray hayatının 19. yüzyıldaki değişimini görünür kılar. Geleneksel mekân düzeni, barok ve neoklasik bezeme anlayışıyla bir araya gelir.|Muayede Salonu, anıtsal kapılar ve deniz cephesi.|palace
Beylerbeyi Sarayı|saray|Üsküdar|Osmanlı|19. yüzyıl|Boğaz’ın Anadolu kıyısında yer alan saray, yazlık kullanım ve konuk ağırlama geleneğinin önemli bir örneğidir. Deniz kıyısı köşkleri ve bahçe ilişkisi, yapının okunmasında belirleyicidir.|Mermer cephe, bahçe terasları ve deniz köşkleri.|palace
Yıldız Sarayı|saray|Beşiktaş|Osmanlı|19. yüzyıl|Yıldız sırtlarında farklı dönemlerde gelişen saray yerleşkesi, yönetim yapılarıyla köşkleri ve bahçeleri bir araya getirir. Topografyaya yayılan düzeni, Dolmabahçe’nin tek kütleli kompozisyonundan farklı bir saray deneyimi sunar.|Avlular, köşkler ve peyzaj ile yapı arasındaki ilişki.|palace
Küçüksu Kasrı|saray|Beykoz|Osmanlı|19. yüzyıl|Göksu ile Küçüksu çevresindeki mesire kültürünün saray mimarisindeki karşılığıdır. Küçük ölçeğine rağmen zengin taş işçiliği ve Boğaz’a dönük cephesiyle dikkat çeker.|Cephedeki kabartmalar, merdivenler ve kıyı görünümü.|palace
Ihlamur Kasırları|saray|Beşiktaş|Osmanlı|19. yüzyıl|Merasim ve Maiyet köşklerinden oluşan yerleşke, yoğun şehir dokusu içinde bir saray bahçesi deneyimi sunar. Taş bezemeler ile ağaçların çevrelediği küçük yapılar, Osmanlı’nın son dönem dinlenme mimarisini anlatır.|Merasim Köşkü’nün dış süslemeleri ve bahçe.|palace
Aynalıkavak Kasrı|saray|Beyoğlu|Osmanlı|18.–19. yüzyıl|Haliç kıyısındaki eski tersane sarayından günümüze ulaşan yapı, Osmanlı köşk mimarisinin zarif örneklerindendir. Ahşap ağırlıklı iç mekân, yazılar ve müzik kültürüyle kurduğu bağ üzerinden okunabilir.|İç mekân tavanları, yazı kuşakları ve Haliç ilişkisi.|palace
Beykoz Mecidiye Kasrı|saray|Beykoz|Osmanlı|19. yüzyıl|Beykoz’un yeşil dokusu içinde yükselen kasır, taş cepheleri ve geniş bahçesiyle kıyıdaki saray yapılarından ayrılır. Mimariyi yalnız binada değil, teras ve peyzaj düzeninde de okumak gerekir.|Simetrik cephe ve bahçe terasları.|palace
İstanbul Arkeoloji Müzeleri|muze|Fatih|Osmanlı|1891|Arkeoloji Müzesi, Eski Şark Eserleri Müzesi ve Çinili Köşk’ten oluşan kompleks, İstanbul’un müzecilik tarihinin merkezlerinden biridir. Koleksiyonlar farklı coğrafyaların tarihini bir araya getirir; neoklasik ana bina da başlı başına bir mimari eserdir.|İskender Lahdi, lahitler ve Çinili Köşk’ün çinileri.|museum
Türk ve İslam Eserleri Müzesi|muze|Fatih|Cumhuriyet|1914 / 1983|İbrahim Paşa Sarayı’nda yer alan müze, halı, el yazması, metal ve seramik eserlerle Türk ve İslam sanatlarını anlatır. Hipodrom’a bakan saray dokusu, koleksiyonun tarihsel atmosferini tamamlar.|Halı koleksiyonu, el yazmaları ve sarayın terası.|museum
Pera Müzesi|muze|Beyoğlu|Cumhuriyet|2005|Beyoğlu’nun kültür hayatında önemli bir durak olan müze, Oryantalist Resim, Anadolu Ağırlık ve Ölçüleri ile Kütahya Çini ve Seramikleri koleksiyonlarıyla tanınır. Yapı ile sergiler birlikte bir kent ve sanat okumasına imkân verir.|Kalıcı koleksiyonlar ve dönemsel sergiler.|city
Sakıp Sabancı Müzesi|muze|Sarıyer|Cumhuriyet|2002|Emirgan’daki Atlı Köşk ile galeriler, kitap sanatları ve hat koleksiyonunu Boğaz manzarasıyla buluşturur. Müze ziyareti, köşk yaşamı, bahçe ve sergi mekânları arasında ilerleyen bir deneyimdir.|Hat eserleri, köşk odaları ve bahçe.|city
Rahmi M. Koç Müzesi|muze|Beyoğlu|Cumhuriyet|1994|Hasköy’de Haliç kıyısındaki endüstriyel miras yapılarında ulaşım, sanayi ve iletişim tarihine odaklanır. Araçlar, makineler ve modeller, İstanbul tarihine günlük hayat ve üretim üzerinden yaklaşmayı sağlar.|Ulaşım koleksiyonu ve eski endüstri yapıları.|city
İstanbul Modern|muze|Beyoğlu|Cumhuriyet|2004|Karaköy kıyısında modern ve çağdaş sanat için bir buluşma noktasıdır. Sanat koleksiyonu kadar denizle ilişki kuran müze mimarisi de İstanbul’un güncel kültür peyzajının parçasıdır.|Sergiler, kıyı cephesi ve teras manzarası.|city
Deniz Müzesi|muze|Beşiktaş|Osmanlı|1897|Osmanlı ve Türkiye denizcilik mirasını bir araya getiren müze, Beşiktaş kıyısında yer alır. Deniz tarihi, yalnız savaş gemileriyle değil, saray kayıkları ve denizle kurulan gündelik ilişki üzerinden de okunur.|Saltanat kayıkları ve ahşap işçiliği.|museum
Sadberk Hanım Müzesi|muze|Sarıyer|Cumhuriyet|1980|Büyükdere’deki müze, arkeolojik eserleri ve Osmanlı dönemi Türk-İslam sanatlarını bir araya getirir. Boğaz kıyısındaki konut dokusu, eserleri şehirdeki yaşam kültürüyle birlikte düşünmek için anlamlı bir çevre sunar.|Arkeoloji koleksiyonu, tekstil ve geleneksel el sanatları.|city
Milli Saraylar Resim Müzesi|muze|Beşiktaş|Cumhuriyet|2014|Dolmabahçe yerleşkesindeki Veliaht Dairesi, resim koleksiyonunu saray mimarisi içinde sunar. Osmanlı’nın son dönemindeki görsel kültür, portre ve manzara geleneği üzerinden izlenebilir.|Manzara resimleri ve Veliaht Dairesi’nin mekânları.|palace
İstanbul Oyuncak Müzesi|muze|Kadıköy|Cumhuriyet|2005|Göztepe’deki müze, farklı dönemlerden oyuncaklarla çocukluk ve gündelik hayat tarihine bakar. Küçük nesneler üzerinden teknolojinin, tasarımın ve hayal dünyasının değişimini keşfetmek mümkündür.|Dönemlere göre oyuncak tasarımları.|city
Ayasofya|inanc|Fatih|Bizans|537|İmparator Justinianus döneminde tamamlanan yapı, büyük kubbesi ve taşıyıcı sistemiyle mimarlık tarihinin dönüm noktalarındandır. Bizans ve Osmanlı katmanları aynı mekânda okunur; yapının bugünkü kullanımında ibadet düzeni ve ziyaret kuralları birlikte gözetilir.|Kubbe geçişleri, mermer kaplamalar ve mozaik katmanları.|unesco
Süleymaniye Camii|inanc|Fatih|Osmanlı|1557|Mimar Sinan’ın tasarladığı külliye, Haliç’e bakan tepede cami, eğitim ve sosyal hizmet yapılarıyla bir şehir parçası oluşturur. Denge, oran ve peyzaj ilişkisi, yapıyı İstanbul siluetinin belirleyici öğelerinden biri yapar.|Avlu oranları, kubbe düzeni ve Haliç görünümü.|unesco
Sultanahmet Camii|inanc|Fatih|Osmanlı|17. yüzyıl|Ayasofya’nın karşısında yükselen külliye, Osmanlı klasik mimarisinin anıtsal örneklerindendir. İç mekândaki çini bezemeler ve kademelenen kubbeler, ışıkla birlikte mekânın karakterini oluşturur.|İznik çinileri, avlu ve kademeli kubbe kompozisyonu.|city
Rüstem Paşa Camii|inanc|Fatih|Osmanlı|16. yüzyıl|Eminönü’nün ticaret dokusu içinde yükseltilmiş bir platform üzerine kurulan Mimar Sinan yapısıdır. Çini kaplamaları, küçük ölçekli bir caminin ne kadar zengin bir iç mekâna dönüşebileceğini gösterir.|Çini panolardaki bitkisel desenler.|city
Ortaköy Camii|inanc|Beşiktaş|Osmanlı|19. yüzyıl|Büyük Mecidiye Camii adıyla da bilinen yapı, kıyı konumuyla Boğaz’ın simgelerindendir. Büyük pencereler, hareketli cepheler ve denizden gelen ışık, 19. yüzyıl Osmanlı mimarisini okumak için belirgin öğelerdir.|Deniz cephesi, taş işçiliği ve pencere oranları.|city
Zeyrek Camii|inanc|Fatih|Bizans|12. yüzyıl|Eski Pantokrator Manastırı’nın kiliselerinden oluşan yapı topluluğu, Bizans’ın manastır mimarisini temsil eder. Çevresindeki tarihî yerleşimle birlikte UNESCO alanının önemli bileşenlerinden biridir.|Tuğla örgüsü, birbirine bağlanan yapı kütleleri.|unesco
Kariye Camii|inanc|Fatih|Bizans|Bizans dönemi|Eski Khora Manastırı kilisesi, Bizans sanatının önemli mozaik ve freskleriyle tanınır. Küçük ölçekli mekânların resim programıyla kurduğu ilişki, büyük kubbeli anıtlardan farklı bir mimari okuma sunar.|Mozaik ve fresklerdeki anlatı dizileri.|city
Aya İrini|inanc|Fatih|Bizans|6. yüzyıl|Topkapı Sarayı’nın ilk avlusunda yer alan kilise, erken Bizans mimarisinin önemli örneklerindendir. Osmanlı döneminde farklı işlevler üstlenen yapıda yalın iç mekân ve apsis düzeni öne çıkar.|Atrium, apsis ve mekânın akustiği.|museum
Küçük Ayasofya Camii|inanc|Fatih|Bizans|6. yüzyıl|Eski Sergios ve Bakhos Kilisesi, Bizans’ın merkezî plan arayışını gösterir. Osmanlı döneminde camiye dönüştürülen yapıda farklı dönemlerin kullanım izleri iç içe geçer.|Sekizgen çekirdek ve çevresindeki galeri.|unesco
Sveti Stefan Kilisesi|inanc|Fatih|Osmanlı|1898|Haliç kıyısındaki Bulgar kilisesi, metal taşıyıcı ve cephe elemanlarıyla İstanbul’un sıra dışı yapılarındandır. Demir Kilise adı, malzemenin yapının kimliğindeki belirleyici rolünü anlatır.|Döküm metal cephe parçaları ve kıyı yerleşimi.|city
Yerebatan Sarnıcı|antik|Fatih|Bizans|6. yüzyıl|Justinianus döneminin büyük su deposu, sütunların oluşturduğu ritmik mekânıyla yeraltında farklı bir İstanbul sunar. Devşirme malzemeler, antik yapı parçalarının yeni işlevlerle yaşatıldığı bir mühendislik dünyasını gösterir.|Sütun sıraları ve Medusa başlı kaideler.|cistern
Şerefiye Sarnıcı|antik|Fatih|Bizans|5. yüzyıl|Şehrin tarihî su altyapısının önemli parçalarından biridir. Sütunlar, tonozlar ve tuğla örgüsü, yeraltı yapılarında işlev ile mimari etkinin nasıl birleştiğini anlatır.|Sütun başlıkları ve tonoz düzeni.|cistern
Binbirdirek Sarnıcı|antik|Fatih|Bizans|Geç Antik Çağ|Sultanahmet çevresindeki büyük kapalı sarnıçlardan biridir. Sütunların taşıdığı tonoz sistemi, kentin su gereksinimini karşılayan yapıların aynı zamanda güçlü bir mekânsal karakter taşıdığını gösterir.|Sütun dizileri ve çift parçalı taşıyıcılar.|cistern
Bozdoğan Kemeri|antik|Fatih|Roma|4. yüzyıl|Valens Kemeri olarak da bilinen su kemeri, Roma dönemindeki büyük su taşıma sisteminin kent içindeki en görünür parçalarındandır. Günümüz trafiğiyle yan yana yaşaması, İstanbul’un katmanlı yapısını açık biçimde gösterir.|Kemer açıklıkları ve taş örgü.|cistern
İstanbul Kara Surları|antik|Fatih|Bizans|5. yüzyıl|Theodosius surları, kent savunmasını duvar, kule ve hendeklerden oluşan çok katmanlı bir sistemle kurar. Tek bir kapı yerine bütün savunma hattını düşünmek, antik başkentin ölçeğini anlamayı sağlar.|Kule aralıkları ve çift duvar sistemi.|unesco
Rumeli Hisarı|antik|Sarıyer|Osmanlı|1452|Boğaz’ın dar kesiminde yer alan hisar, fetih öncesi deniz geçişinin kontrolü için inşa edildi. Araziye uyum sağlayan surları ve büyük kuleleri, askerî mimarinin coğrafyayla ilişkisini gösterir.|Kulelerin farklı biçimleri ve kıyıya inen surlar.|museum
Anadolu Hisarı|antik|Beykoz|Osmanlı|14. yüzyıl|Göksu’nun Boğaz’a açıldığı noktadaki hisar, Anadolu kıyısının tarihî savunma yapılarındandır. Dar su geçidiyle ilişkisi, karşı kıyıdaki Rumeli Hisarı ile birlikte düşünülmelidir.|Ana kule ve nehir ağzındaki konum.|city
Yedikule Hisarı|antik|Fatih|Osmanlı|15. yüzyıl|Bizans kara surları ile Osmanlı döneminde eklenen kulelerin birleştiği yapı, İstanbul’un savunma ve devlet tarihini bir arada taşır. Kapılar, avlu ve kuleler farklı dönemlerde değişen işlevlerin izlerini korur.|Altın Kapı çevresi ve kule-avlu düzeni.|city
Sultanahmet Meydanı|semt|Fatih|Bizans|Çok katmanlı|Antik Hipodrom’un izlerini taşıyan meydan, Bizans kamusal hayatıyla Osmanlı tören kültürünü aynı zeminde buluşturur. Çevresindeki büyük anıtlar, şehrin farklı dönemlerini yürüyerek karşılaştırma imkânı verir.|Dikilitaş, Yılanlı Sütun ve meydanın uzun aksı.|city
Fener & Balat|semt|Fatih|Osmanlı|Çok katmanlı|Haliç kıyısındaki mahalleler, ibadethaneleri, yokuşları ve farklı dönemlerden konutlarıyla İstanbul’un çok kültürlü hafızasını taşır. Renkli cephelerin arkasında yaşayan bir mahalle olduğunu hatırlayarak keşfetmek gerekir.|Konut cepheleri, Haliç kıyısı ve yokuş sokaklar.|city
Kuzguncuk|semt|Üsküdar|Osmanlı|Çok katmanlı|Boğaz kıyısındaki mahalle, ahşap evler, bahçeler ve farklı inanç yapılarıyla güçlü bir yerel kimlik taşır. Sokak ölçeği, anıtsal yapılar yerine gündelik mimari üzerinden İstanbul’u anlatır.|Ahşap cepheler ve sokak-bahçe ilişkisi.|city
Galata & Karaköy|semt|Beyoğlu|Osmanlı|Çok katmanlı|Kule çevresindeki yokuşlar ile liman kıyısındaki ticaret dokusu, şehrin deniz aşırı bağlantılarını görünür kılar. Hanlar, apartmanlar ve ibadethaneler birlikte okunduğunda bölgenin tek bir döneme ait olmadığı anlaşılır.|Kule çevresi, banka binaları ve limana inen sokaklar.|city
Beyoğlu & İstiklal|semt|Beyoğlu|Osmanlı|19.–20. yüzyıl|Pasajlar, apartmanlar, ibadethaneler ve kültür yapıları, İstanbul’un modernleşme tarihinin katmanlarını taşır. Ana caddenin dışındaki sokaklar da mimari çeşitliliği görmek için önemli duraklardır.|Pasaj girişleri ve üst katlardaki cephe ayrıntıları.|city
Kadıköy & Moda|semt|Kadıköy|Cumhuriyet|Çok katmanlı|Çarşı, kıyı ve konut sokakları arasında değişen bir kent deneyimi sunar. Tarihî apartmanlar, kültür mekânları ve denizle kurulan gündelik ilişki, Anadolu yakasının şehir hafızasını anlatır.|Eski apartmanlar, çarşı sokakları ve sahil.|city
Üsküdar|semt|Üsküdar|Osmanlı|Çok katmanlı|Meydan, iskele ve külliyeler çevresinde gelişen Üsküdar, Osmanlı İstanbul’unun Anadolu kıyısındaki önemli merkezidir. Mihrimah Sultan ve Yeni Valide külliyeleri kıyıdaki kamusal mekânın biçimlenmesinde rol oynar.|İskele meydanı, çeşmeler ve külliye avluları.|city
Kapalıçarşı|carsi|Fatih|Osmanlı|15. yüzyıl|Bedestenler çevresinde gelişen çarşı, yüzyıllar boyunca İstanbul ticaretinin merkezlerinden biri oldu. Örtülü sokaklar, dükkânlar ve han bağlantıları, bir bina kadar bir kent dokusu gibi okunmalıdır.|Bedestenler, tonozlu sokaklar ve han geçitleri.|city
Mısır Çarşısı|carsi|Fatih|Osmanlı|17. yüzyıl|Yeni Cami çevresindeki külliye ve ticaret dokusuyla ilişkilidir. Baharat ve gıda ticaretiyle anılan çarşı, Eminönü’nün gündelik hareketi içinde tarihî bir yapı olarak yaşamayı sürdürür.|L biçimli plan ve çevredeki ticaret sokakları.|city
Büyük Valide Han|carsi|Fatih|Osmanlı|17. yüzyıl|Eminönü hanlar bölgesindeki yapı, ticaret ve konaklama işlevlerini avlular etrafında birleştirir. Han kültürü, şehirde malların dolaşımı kadar esnaf ve zanaatkârların ortak yaşamını da anlatır.|Avlular ve dükkân-atölye düzeni; özel alanlara izinsiz girilmemeli.|city
Çiçek Pasajı|carsi|Beyoğlu|Osmanlı|19. yüzyıl|İstiklal Caddesi üzerindeki pasaj, geç Osmanlı döneminin ticaret ve eğlence mekânları arasında yer alır. Cam örtü, cephe süslemeleri ve dar iç sokak, Avrupa etkili pasaj mimarisini İstanbul ölçeğinde gösterir.|Üst kat cepheleri ve iç geçidin örtüsü.|city
Arasta Çarşısı|carsi|Fatih|Osmanlı|17. yüzyıl|Sultanahmet Camii yakınındaki arasta, külliye ile ticari hayat arasındaki ilişkiyi gösterir. Küçük ölçekli dükkân sıraları, büyük anıtların çevresindeki gündelik ekonomik düzenin parçasıdır.|Dükkân ritmi ve külliye ile komşuluk.|city
Sahaflar Çarşısı|carsi|Fatih|Osmanlı|Tarihî gelenek|Beyazıt çevresinde kitap ticaretinin ve okuma kültürünün hafızasını taşır. Basılı eserler, eski kitaplar ve çarşı düzeni, İstanbul’u yalnız yapılarla değil bilgi dolaşımıyla da düşünmeye davet eder.|Kitapçı dükkânları ve Beyazıt çevresindeki kültür dokusu.|city
Emirgan Korusu|bosphorus|Sarıyer|Osmanlı|Çok katmanlı|Boğaz’a bakan yamaçlarda ağaçlar, yürüyüş yolları ve köşkler bir araya gelir. Koru, İstanbul’un tarihî peyzajını ve kent içinde yeşil alanla kurulan ilişkiyi anlamak için önemli bir duraktır.|Köşkler, ağaç dokusu ve kıyıya açılan manzaralar.|city
Yıldız Parkı|bosphorus|Beşiktaş|Osmanlı|19. yüzyıl|Saray çevresindeki bahçe geleneğinin izlerini taşıyan park, yoğun şehir dokusu içinde yeşil bir ara durak oluşturur. Eğimli arazi, ağaçlar ve köşkler birbirinden farklı yürüyüş deneyimleri sunar.|Peyzaj içinde köşklerin yerleşimi.|city
Gülhane Parkı|bosphorus|Fatih|Osmanlı|Çok katmanlı|Topkapı Sarayı çevresindeki tarihî bahçe alanı, bugün Tarihî Yarımada’da açık hava yürüyüşü için bir duraktır. Saray, müzeler ve Sarayburnu arasında bir bağlantı kurar.|Ağaçlı yollar ve saray duvarlarıyla ilişki.|city
Büyükada|bosphorus|Adalar|Osmanlı|19.–20. yüzyıl|Ahşap köşkler, bahçeler ve ada topografyası, İstanbul’un sayfiye kültürünü anlatır. Kıyı yerleşiminden yamaçlara doğru çıkıldıkça konut dokusu ile doğal peyzaj arasındaki ilişki belirginleşir.|Ahşap köşk cepheleri ve bahçe duvarları.|city
Bebek & Arnavutköy Kıyısı|bosphorus|Beşiktaş|Osmanlı|Çok katmanlı|Boğaz kıyısındaki yerleşim, yalılar, ahşap evler ve iskelelerle denizle birlikte gelişen bir mimariyi gösterir. Sahil yürüyüşü, cepheleri ve kıyı çizgisindeki değişimleri karşılaştırmaya imkân verir.|Yalı cepheleri ve kıyı boyunca yerleşim ritmi.|city
Fethi Paşa Korusu|bosphorus|Üsküdar|Osmanlı|19. yüzyıl|Anadolu yakasında Boğaz’a bakan yeşil alan, tarihî koru peyzajının kent içindeki örneklerindendir. Yamaçta değişen görüş noktaları, şehri karşı kıyıdan okumak için farklı bakışlar sunar.|Ağaç dokusu ve Boğaz manzaraları.|city
Galata Kulesi|sivil|Beyoğlu|Ceneviz|1348|Galata’nın tepesindeki kule, Ceneviz yerleşiminin savunma mirasını ve sonraki dönemlerin kullanım izlerini taşır. Çevresindeki yokuşlu sokak dokusu, kulenin şehir içindeki konumunu anlamak için önemlidir.|Taş gövde, pencere açıklıkları ve panoramik kent okuması.|museum
Kız Kulesi|sivil|Üsküdar|Osmanlı|Çok katmanlı|Salacak açıklarındaki küçük ada üzerinde yer alan yapı, farklı dönemlerde yenilenen deniz yapılarının simgesidir. Efsaneleriyle tarihî kullanımını ayırarak okumak, kulenin kent belleğindeki yerini daha iyi anlamayı sağlar.|Ada-kıyı ilişkisi ve denizden şehir silueti.|museum
Haydarpaşa Garı|sivil|Kadıköy|Osmanlı|1908|Anadolu demiryollarının İstanbul’daki simgesel başlangıç noktası, denize dönük anıtsal cephesiyle tanınır. Ulaşım tarihinin yanı sıra kent ile kıyı arasındaki ilişkiyi de temsil eder.|Simetrik cephe ve denize dönük yerleşim; erişim duyuruları kontrol edilmeli.|city
Sirkeci Garı|sivil|Fatih|Osmanlı|1890|Avrupa demiryolu bağlantısının tarihî terminali, doğu ve batı esintilerini birleştiren cephe diliyle dikkat çeker. Garı Eminönü’nün ulaşım ve ticaret dokusuyla birlikte okumak gerekir.|Pencere biçimleri ve taş-tuğla birlikteliği.|city
III. Ahmed Çeşmesi|sivil|Fatih|Osmanlı|1728|Topkapı Sarayı’nın giriş yakınındaki meydan çeşmesi, su yapılarının kamusal hayat içindeki rolünü gösterir. Saçak, yazı ve bitkisel süsleme, Lale Devri’nin bezeme anlayışını küçük bir yapıda bir araya getirir.|Geniş saçak ve cephelerdeki kitabeler.|city
Alman Çeşmesi|sivil|Fatih|Osmanlı|1901|Sultanahmet Meydanı’ndaki çeşme, geç Osmanlı döneminin uluslararası ilişkilerini anıtsal bir kamusal yapıya dönüştürür. Kubbe, sütunlar ve mozaikler meydandaki daha eski anıtlarla yan yana okunur.|Kubbe içi mozaikler ve sütun düzeni.|city
Tekfur Sarayı|sivil|Fatih|Bizans|Geç Bizans|Kara surları çevresindeki Bizans saray kalıntısı, tuğla ve taşın birlikte kullanıldığı cepheleriyle öne çıkar. Osmanlı dönemindeki çini üretimiyle de ilişkili olan yapı, farklı kullanım katmanlarını bir arada taşır.|Cephedeki renkli örgü ve çini geleneği.|city
`;
const PLACES=ROWS.trim().split('\n').map((line,i)=>{const [name,category,district,era,date,story,look,source]=line.split('|');return {id:String(i+1),name,category,district,era,date,story,look,source};});
const EXTRA={
'1':{history:'Fatih Sultan Mehmed döneminde 1460–1478 arasında kurulan saray, sonraki padişahların eklemeleriyle büyüdü. Yaklaşık dört yüzyıl yönetim, eğitim ve sanatın merkezlerinden biri oldu. Cumhuriyet döneminde 1924 yılında müzeye dönüştürüldü.',architecture:'Birbirini izleyen avlular, kamusal alandan sarayın daha özel bölümlerine doğru ilerleyen bir mekân düzeni kurar. Köşkler, revaklar ve bahçeler tek bir büyük yapının yerine zaman içinde oluşmuş bir bütün yaratır.',link:'https://millisaraylar.gov.tr/Lokasyon/2/Topkapi-Sarayi'},
'2':{history:'1843–1856 arasında inşa edilen saray, Osmanlı yönetiminin ve saray hayatının Boğaz kıyısına taşınmasını temsil eder. Cumhuriyet döneminde Atatürk tarafından da kullanıldı; Atatürk 10 Kasım 1938’de burada hayatını kaybetti.',architecture:'Selamlık, Harem ve Muayede Salonu farklı işlevleri bir araya getirir. Geleneksel Osmanlı mekân alışkanlıkları, Avrupa etkili süsleme ve anıtsal cephe düzeniyle yeniden yorumlanır.',link:'https://millisaraylar.gov.tr/Lokasyon/3/Dolmabahce-Sarayi'},
'9':{history:'Osman Hamdi Bey’in müzecilik ve kazı çalışmaları, koleksiyonun ve müze binasının gelişiminde belirleyici oldu. Alexander Vallaury’nin tasarladığı klasik bina 13 Haziran 1891’de açıldı.',architecture:'Neoklasik ana bina, müze işlevi için tasarlanmış önemli bir yapıdır. Kompleksin içindeki Çinili Köşk ise daha erken Osmanlı sivil mimarisini ve çini geleneğini temsil eder.',link:'https://muze.gov.tr/muze-detay?DistId=IAR&SectionId=IAR01'},
'19':{history:'532–537 arasında Anthemios ve Isidoros tarafından tasarlanan yapı, Bizans başkentinin büyük kilisesiydi. Osmanlı dönemindeki eklemeler yapının siluetini ve iç mekânını yeni katmanlarla zenginleştirdi.',architecture:'Merkezî kubbe, yarım kubbeler ve taşıyıcı ayaklar, büyük bir iç hacim oluşturur. Mermer yüzeyler ile farklı dönemlerin bezemeleri bir arada incelenebilir.',link:'https://whc.unesco.org/en/list/356/'},
'20':{history:'1550–1557 arasında Mimar Sinan tarafından tasarlanan külliye, Kanuni Sultan Süleyman döneminin mimari ve sosyal düzenini temsil eder.',architecture:'Caminin avlu, kubbe ve yan hacimleri güçlü bir oran ilişkisi kurar. Çevresindeki eğitim ve sosyal hizmet yapıları, anıtın bir şehir sistemi içinde düşünülmesini sağlar.',link:'https://whc.unesco.org/en/list/356/'}
};
const ROUTES=[
{name:'Tarihî Yarımada',label:'BİR GÜNLÜK KEŞİF',desc:'İmparatorlukların merkezinde, meydanlardan saray avlularına.',stops:['19','21','37','29','1','9'],image:'topkapi'},
{name:'Haliç’in iki yakası',label:'MAHALLELER & BELLEK',desc:'Kubbeler, renkli sokaklar ve endüstriyel miras arasında.',stops:['20','24','38','28','13'],image:'istanbul'},
{name:'Boğaz’ın sarayları',label:'MİMARİ & KIYI',desc:'Kıyı boyunca saray mimarisinin değişen yüzünü izle.',stops:['2','4','3','5','8'],image:'palace'},
{name:'Anadolu yakasının ruhu',label:'SOKAKLAR & MANZARALAR',desc:'Salacak’tan Kuzguncuk’a, kıyıdaki farklı İstanbul.',stops:['57','43','39','55','58','42'],image:'bosphorus'}
];
